project:
  type: website
  output-dir: docs

website:
  title: "Social Alchemy Hub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me

format:
  html:
    theme: cyborg
    css: styles.css
    page-layout: full
    toc: true



